## **NumPy: Arrays and Matrices**

> NumPy is an extension to the Python Programming language. Adding support for large, multi-dimensional (numerical) arrays and matrices, along with a large library of high-level methematical functions to operate on these arrays. NumPy is having the full form **Numeric Python**.

In [2]:
# importing required modules
import numpy as np

In [6]:
# creating ndarrays from lists
# in ndarray all the data items will have the same data types
data1 = [11, 22, 44, 33, 66, 55]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)   # len will give us the first dimension of the ndarray

[11, 22, 44, 33, 66, 55] 6 <class 'list'> 1294413236864
[11 22 44 33 66 55] 6 <class 'numpy.ndarray'> 1294396469584 int32


In [7]:
data1 = [11, 22., 44, 33, 66, 55]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)

[11, 22.0, 44, 33, 66, 55] 6 <class 'list'> 1294426355008
[11. 22. 44. 33. 66. 55.] 6 <class 'numpy.ndarray'> 1294425294960 float64


In [8]:
data1 = [11, False, 22, 44, True, 33, 66, 55]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)

[11, False, 22, 44, True, 33, 66, 55] 8 <class 'list'> 1294411870144
[11  0 22 44  1 33 66 55] 8 <class 'numpy.ndarray'> 1294425296400 int32


In [9]:
data1 = [11, False, 22.0, 44, True, 33, 66, 55]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)

[11, False, 22.0, 44, True, 33, 66, 55] 8 <class 'list'> 1294426426176
[11.  0. 22. 44.  1. 33. 66. 55.] 8 <class 'numpy.ndarray'> 1294425296112 float64


In [10]:
data1 = [11, False, 22., "44", True, 33, 66, 55]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)

[11, False, 22.0, '44', True, 33, 66, 55] 8 <class 'list'> 1294425221504
['11' 'False' '22.0' '44' 'True' '33' '66' '55'] 8 <class 'numpy.ndarray'> 1294413496752 <U32


In [16]:
data1 = range(1, 10)
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)
list1 = arr1.tolist()
print (list1, len(list1), type(list1), id(list1))

range(1, 10) 9 <class 'range'> 1294416930352
[1 2 3 4 5 6 7 8 9] 9 <class 'numpy.ndarray'> 1294425296400 int32
[1, 2, 3, 4, 5, 6, 7, 8, 9] 9 <class 'list'> 1294415556736


In [14]:
data2 = [[11, 22, 44, 33, 66], [55, 99, 88, 77, 34]]
print (data2, len(data2), type(data2), id(data2))
arr2 = np.array(data2)
print (arr2, len(arr2), type(arr2), id(arr2), arr2.dtype)

[[11, 22, 44, 33, 66], [55, 99, 88, 77, 34]] 2 <class 'list'> 1294426426176
[[11 22 44 33 66]
 [55 99 88 77 34]] 2 <class 'numpy.ndarray'> 1294405653968 int32


In [18]:
data2 = [[11, False, 44, '33', 66], [55, 99, 88., True, 34]]
print (data2, len(data2), type(data2), id(data2))
arr2 = np.array(data2)
print (arr2, len(arr2), type(arr2), id(arr2), arr2.dtype)
list2 = arr2.tolist()
print (list2, len(list2), type(list2), id(list2))

[[11, False, 44, '33', 66], [55, 99, 88.0, True, 34]] 2 <class 'list'> 1294406004480
[['11' 'False' '44' '33' '66']
 ['55' '99' '88.0' 'True' '34']] 2 <class 'numpy.ndarray'> 1294425296304 <U32
[['11', 'False', '44', '33', '66'], ['55', '99', '88.0', 'True', '34']] 2 <class 'list'> 1294406001856


In [29]:
# examining arrays
arr1 = np.array([22, 44, 33, 66, 55, 88, 77])
print (arr1, type(arr1), id(arr1))
print (arr1.dtype, arr1.shape, len(arr1), arr1.ndim, arr1.size)
print ()
arr2 = np.array([[22, 44, 33, 66], [55, 88, 77, 99]])
print (arr2, type(arr2), id(arr2))
print (arr2.dtype, arr2.shape, len(arr2), arr2.ndim, arr2.size)
print ()
arr3 = np.array([[[22, 44, 33, 66], [55, 88, 77, 99], [34, 54, 67, 58]], [[122, 144, 133, 166], [155, 188, 177, 199], [234, 256, 267, 289]]])
print (arr3, type(arr3), id(arr3))
print (arr3.dtype, arr3.shape, len(arr3), arr3.ndim, arr3.size)

[22 44 33 66 55 88 77] <class 'numpy.ndarray'> 1294417776528
int32 (7,) 7 1 7

[[22 44 33 66]
 [55 88 77 99]] <class 'numpy.ndarray'> 1294417775856
int32 (2, 4) 2 2 8

[[[ 22  44  33  66]
  [ 55  88  77  99]
  [ 34  54  67  58]]

 [[122 144 133 166]
  [155 188 177 199]
  [234 256 267 289]]] <class 'numpy.ndarray'> 1294417775376
int32 (2, 3, 4) 2 3 24


In [38]:
# create srecial arrays
print (np.zeros(10))
print (np.zeros(10).astype('int'))
print (np.zeros(10).astype('float'))
print (np.zeros(10, 'int'))
print (np.zeros(10, 'float'))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [50]:
print (np.zeros((3, 6)))
print (np.zeros((3, 6)).astype('int'))
print (np.zeros((3, 6), 'int'))
print (np.zeros((3, 6), dtype = 'int'))
print (np.zeros(18).reshape(2, 9))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [51]:
print (np.ones(10))
print (np.ones(10).astype('int'))
print (np.ones(10).astype('float'))
print (np.ones(10, 'int'))
print (np.ones(10, 'float'))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [52]:
print (np.ones((3, 6)))
print (np.ones((3, 6)).astype('int'))
print (np.ones((3, 6), 'int'))
print (np.ones((3, 6), dtype = 'int'))
print (np.ones(18).reshape(2, 9))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [53]:
print (np.ones(10) * 5)
print (np.ones(10).astype('int') * 5)
print (np.ones(10).astype('float') * 5)
print (np.ones(10, 'int') * 5)
print (np.ones(10, 'float') * 5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5 5 5 5 5 5 5 5 5 5]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5 5 5 5 5 5 5 5 5 5]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [57]:
# reshaping
print (np.ones(18))
print (np.ones(18).astype('int'))
print (np.ones(18).astype('int').reshape(2, 9))
print (np.ones(18).reshape(2, 9).astype('int'))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]
[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]


In [9]:
# arange is like a range, exept it returns an array (not a list)
int_list = range(5)
print (int_list)
for item in int_list:
    print (item, end = ", ")
print ()
int_array = np.arange(5)
print (int_array, type(int_array))
float_array = np.arange(5).astype(float)
print (float_array, type(float_array))

range(0, 5)
0, 1, 2, 3, 4, 
[0 1 2 3 4] <class 'numpy.ndarray'>
[0. 1. 2. 3. 4.] <class 'numpy.ndarray'>


### Reshape, Transpose and Flatten

In [14]:
print (np.arange(20))
print (np.arange(20).reshape(4, 5))
print (np.arange(20).reshape(4, 5).flatten())
print (np.arange(20).reshape(4, 5).T)
print (np.arange(20).reshape(4, 5).transpose())
print (np.arange(20).reshape(4, 5).transpose().flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
[ 0  5 10 15  1  6 11 16  2  7 12 17  3  8 13 18  4  9 14 19]


### Append, Insert, Delete and Sort

In [10]:
matrix = np.arange(10, dtype = np.int8)
print (matrix, len(matrix), matrix.shape, type(matrix))
matrix = np.append(matrix, [10, 11, 12])
print (matrix, len(matrix), matrix.shape, type(matrix))
matrix = np.insert(matrix, 3, [13, 14, 15])
print (matrix, len(matrix), matrix.shape, type(matrix))
matrix = np.delete(matrix, [5, 6, 7])
print (matrix, len(matrix), matrix.shape, type(matrix))
matrix = np.delete(matrix, range(5, 8))
print (matrix, len(matrix), matrix.shape, type(matrix))
matrix = np.sort(matrix)
print (matrix, len(matrix), matrix.shape, type(matrix))
matrix = -np.sort(-matrix)
print (matrix, len(matrix), matrix.shape, type(matrix))

[0 1 2 3 4 5 6 7 8 9] 10 (10,) <class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12] 13 (13,) <class 'numpy.ndarray'>
[ 0  1  2 13 14 15  3  4  5  6  7  8  9 10 11 12] 16 (16,) <class 'numpy.ndarray'>
[ 0  1  2 13 14  5  6  7  8  9 10 11 12] 13 (13,) <class 'numpy.ndarray'>
[ 0  1  2 13 14  8  9 10 11 12] 10 (10,) <class 'numpy.ndarray'>
[ 0  1  2  8  9 10 11 12 13 14] 10 (10,) <class 'numpy.ndarray'>
[14 13 12 11 10  9  8  2  1  0] 10 (10,) <class 'numpy.ndarray'>


### Concatenation and Stack of 2 Arrays

In [17]:
a = np.array([[1, 2], [3, 4]])
print ("First array:")
print (a)
b = np.array([[5, 6], [7, 8]])
print ("Second array:")
print (b)
print ("\n")
# for concatenation both the arrays must be on the same dimensions
print ("Concatenation along axis 0")
print (np.concatenate((a, b), axis = 0))
print ("\n")
print ("Concatenation along axis 1")
print (np.concatenate((a, b), axis = 1))

First array:
[[1 2]
 [3 4]]
Second array:
[[5 6]
 [7 8]]


Concatenation along axis 0
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Concatenation along axis 1
[[1 2 5 6]
 [3 4 7 8]]


In [20]:
print ("Stack the two arrays along axis 0")
print (np.stack((a, b), axis = 0))
print ("\n")
print ("Stack the two arrays along axis 1")
print (np.stack((a, b), axis = 1))
print ("\n")

Stack the two arrays along axis 0
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Stack the two arrays along axis 1
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]




In [24]:
matrix = np.array([[100, 200, 300, 400]])
print (matrix, type(matrix), matrix.shape, matrix.ndim)
arr = matrix.reshape(-1)
print (arr, type(arr), arr.shape, arr.ndim)
arr = matrix.reshape(-1, 1, 4)
print (arr, type(arr), arr.shape, arr.ndim)
arr = matrix.reshape(1, 4, -1)
print (arr, type(arr), arr.shape, arr.ndim)

[[100 200 300 400]] <class 'numpy.ndarray'> (1, 4) 2
[100 200 300 400] <class 'numpy.ndarray'> (4,) 1
[[[100 200 300 400]]] <class 'numpy.ndarray'> (1, 1, 4) 3
[[[100]
  [200]
  [300]
  [400]]] <class 'numpy.ndarray'> (1, 4, 1) 3


### Selection

In [30]:
data1 = [11, 22, 33, 44, 55]
arr1 = np.array(data1)
print (arr1, type(arr1), arr1.dtype, arr1.shape)
print (arr1[0], arr1[2], arr1[-1], arr1[-3])   # indexing
print (arr1[2:], arr1[:3])
print (arr1[::-1])

[11 22 33 44 55] <class 'numpy.ndarray'> int32 (5,)
11 33 55 33
[33 44 55] [11 22 33]
[55 44 33 22 11]


In [31]:
# indexing and slicing
#         L2R ->  0         1          2           3            4         5   
arr1 = np.array(["Monday", "Tuesday", "Saturday", "Wednesday", "Friday", "Thursday"])
#          R2L ->-6         -5         -4          -3           -2        -1 
print (arr1, len(arr1), type(arr1), id(arr1))
print (arr1[3], arr1[-3], arr1[5], arr1[-1])   # indexing
print (arr1[1:5], arr1[-5:-1])
print (arr1[1:-1], arr1[-5:5])
print (arr1[:3], arr1[:-3])
print (arr1[3:], arr1[-3:])
print (arr1[3][3:6])

['Monday' 'Tuesday' 'Saturday' 'Wednesday' 'Friday' 'Thursday'] 6 <class 'numpy.ndarray'> 2342112560304
Wednesday Wednesday Thursday Thursday
['Tuesday' 'Saturday' 'Wednesday' 'Friday'] ['Tuesday' 'Saturday' 'Wednesday' 'Friday']
['Tuesday' 'Saturday' 'Wednesday' 'Friday'] ['Tuesday' 'Saturday' 'Wednesday' 'Friday']
['Monday' 'Tuesday' 'Saturday'] ['Monday' 'Tuesday' 'Saturday']
['Wednesday' 'Friday' 'Thursday'] ['Wednesday' 'Friday' 'Thursday']
nes


In [38]:
data2 = [range(1, 5), range(5, 9)]  # list of lists
arr2 = np.array(data2)
print (arr2, type(arr2), arr2.dtype, arr2.shape, arr2.ndim)
print (arr2[1, 2], arr2[1][2], arr2[0, :], arr2[1, :])
print (arr2[:, 1:3])

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> int32 (2, 4) 2
7 7 [1 2 3 4] [5 6 7 8]
[[2 3]
 [6 7]]


### Views and Copies

In [45]:
arr = np.arange(10)
print (arr, arr[5:8])
arr[5: 8] = 100
print (arr)
arr_view = arr[5: 8]  # creating a view
print (arr_view)
arr[5: 8] = 500
print (arr, arr_view)
arr_copy = arr[5: 8].copy()  # creating a copy
print (arr_copy)
arr[5: 8] = 800
print (arr, arr_copy)

[0 1 2 3 4 5 6 7 8 9] [5 6 7]
[  0   1   2   3   4 100 100 100   8   9]
[100 100 100]
[  0   1   2   3   4 500 500 500   8   9] [500 500 500]
[500 500 500]
[  0   1   2   3   4 800 800 800   8   9] [500 500 500]


In [50]:
list1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print (list1, list1[5:8])
list1[5: 8] = [100, 100, 100]
print (list1)
list_view = list1[5: 8]  # creating a view
print (list_view)
list1[5: 8] = [500, 500, 500]
print (list1, list_view)
list_copy = list1[5: 8].copy()  # creating a copy
print (list_copy)
list1[5: 8] = [800, 800, 800]
print (list1, list_copy)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] [5, 6, 7]
[0, 1, 2, 3, 4, 100, 100, 100, 8, 9]
[100, 100, 100]
[0, 1, 2, 3, 4, 500, 500, 500, 8, 9] [100, 100, 100]
[500, 500, 500]
[0, 1, 2, 3, 4, 800, 800, 800, 8, 9] [500, 500, 500]


### Using Boolean Arrays