## **NumPy: Arrays and Matrices**

> NumPy is an extension to the Python Programming language. Adding support for large, multi-dimensional (numerical) arrays and matrices, along with a large library of high-level methematical functions to operate on these arrays. NumPy is having the full form **Numeric Python**.

In [2]:
# importing required modules
import numpy as np

In [6]:
# creating ndarrays from lists
# in ndarray all the data items will have the same data types
data1 = [11, 22, 44, 33, 66, 55]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)   # len will give us the first dimension of the ndarray

[11, 22, 44, 33, 66, 55] 6 <class 'list'> 1294413236864
[11 22 44 33 66 55] 6 <class 'numpy.ndarray'> 1294396469584 int32


In [7]:
data1 = [11, 22., 44, 33, 66, 55]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)

[11, 22.0, 44, 33, 66, 55] 6 <class 'list'> 1294426355008
[11. 22. 44. 33. 66. 55.] 6 <class 'numpy.ndarray'> 1294425294960 float64


In [8]:
data1 = [11, False, 22, 44, True, 33, 66, 55]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)

[11, False, 22, 44, True, 33, 66, 55] 8 <class 'list'> 1294411870144
[11  0 22 44  1 33 66 55] 8 <class 'numpy.ndarray'> 1294425296400 int32


In [9]:
data1 = [11, False, 22.0, 44, True, 33, 66, 55]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)

[11, False, 22.0, 44, True, 33, 66, 55] 8 <class 'list'> 1294426426176
[11.  0. 22. 44.  1. 33. 66. 55.] 8 <class 'numpy.ndarray'> 1294425296112 float64


In [10]:
data1 = [11, False, 22., "44", True, 33, 66, 55]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)

[11, False, 22.0, '44', True, 33, 66, 55] 8 <class 'list'> 1294425221504
['11' 'False' '22.0' '44' 'True' '33' '66' '55'] 8 <class 'numpy.ndarray'> 1294413496752 <U32


In [16]:
data1 = range(1, 10)
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)
list1 = arr1.tolist()
print (list1, len(list1), type(list1), id(list1))

range(1, 10) 9 <class 'range'> 1294416930352
[1 2 3 4 5 6 7 8 9] 9 <class 'numpy.ndarray'> 1294425296400 int32
[1, 2, 3, 4, 5, 6, 7, 8, 9] 9 <class 'list'> 1294415556736


In [14]:
data2 = [[11, 22, 44, 33, 66], [55, 99, 88, 77, 34]]
print (data2, len(data2), type(data2), id(data2))
arr2 = np.array(data2)
print (arr2, len(arr2), type(arr2), id(arr2), arr2.dtype)

[[11, 22, 44, 33, 66], [55, 99, 88, 77, 34]] 2 <class 'list'> 1294426426176
[[11 22 44 33 66]
 [55 99 88 77 34]] 2 <class 'numpy.ndarray'> 1294405653968 int32


In [18]:
data2 = [[11, False, 44, '33', 66], [55, 99, 88., True, 34]]
print (data2, len(data2), type(data2), id(data2))
arr2 = np.array(data2)
print (arr2, len(arr2), type(arr2), id(arr2), arr2.dtype)
list2 = arr2.tolist()
print (list2, len(list2), type(list2), id(list2))

[[11, False, 44, '33', 66], [55, 99, 88.0, True, 34]] 2 <class 'list'> 1294406004480
[['11' 'False' '44' '33' '66']
 ['55' '99' '88.0' 'True' '34']] 2 <class 'numpy.ndarray'> 1294425296304 <U32
[['11', 'False', '44', '33', '66'], ['55', '99', '88.0', 'True', '34']] 2 <class 'list'> 1294406001856


In [29]:
# examining arrays
arr1 = np.array([22, 44, 33, 66, 55, 88, 77])
print (arr1, type(arr1), id(arr1))
print (arr1.dtype, arr1.shape, len(arr1), arr1.ndim, arr1.size)
print ()
arr2 = np.array([[22, 44, 33, 66], [55, 88, 77, 99]])
print (arr2, type(arr2), id(arr2))
print (arr2.dtype, arr2.shape, len(arr2), arr2.ndim, arr2.size)
print ()
arr3 = np.array([[[22, 44, 33, 66], [55, 88, 77, 99], [34, 54, 67, 58]], [[122, 144, 133, 166], [155, 188, 177, 199], [234, 256, 267, 289]]])
print (arr3, type(arr3), id(arr3))
print (arr3.dtype, arr3.shape, len(arr3), arr3.ndim, arr3.size)

[22 44 33 66 55 88 77] <class 'numpy.ndarray'> 1294417776528
int32 (7,) 7 1 7

[[22 44 33 66]
 [55 88 77 99]] <class 'numpy.ndarray'> 1294417775856
int32 (2, 4) 2 2 8

[[[ 22  44  33  66]
  [ 55  88  77  99]
  [ 34  54  67  58]]

 [[122 144 133 166]
  [155 188 177 199]
  [234 256 267 289]]] <class 'numpy.ndarray'> 1294417775376
int32 (2, 3, 4) 2 3 24


In [38]:
# create srecial arrays
print (np.zeros(10))
print (np.zeros(10).astype('int'))
print (np.zeros(10).astype('float'))
print (np.zeros(10, 'int'))
print (np.zeros(10, 'float'))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [50]:
print (np.zeros((3, 6)))
print (np.zeros((3, 6)).astype('int'))
print (np.zeros((3, 6), 'int'))
print (np.zeros((3, 6), dtype = 'int'))
print (np.zeros(18).reshape(2, 9))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [51]:
print (np.ones(10))
print (np.ones(10).astype('int'))
print (np.ones(10).astype('float'))
print (np.ones(10, 'int'))
print (np.ones(10, 'float'))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [52]:
print (np.ones((3, 6)))
print (np.ones((3, 6)).astype('int'))
print (np.ones((3, 6), 'int'))
print (np.ones((3, 6), dtype = 'int'))
print (np.ones(18).reshape(2, 9))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [53]:
print (np.ones(10) * 5)
print (np.ones(10).astype('int') * 5)
print (np.ones(10).astype('float') * 5)
print (np.ones(10, 'int') * 5)
print (np.ones(10, 'float') * 5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5 5 5 5 5 5 5 5 5 5]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5 5 5 5 5 5 5 5 5 5]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [57]:
# reshaping
print (np.ones(18))
print (np.ones(18).astype('int'))
print (np.ones(18).astype('int').reshape(2, 9))
print (np.ones(18).reshape(2, 9).astype('int'))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]
[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]
